from app.models import Municipio
from app import db  

municipios_seed = [
    {"nombre": "Abadiño", "pais": "Euskal Herria", "codigo": 7708, "tiene_municipio": True},
    {"nombre": "Abanto y Ciérvana-Abanto Zierbena", "pais": "Euskal Herria", "codigo": 9254, "tiene_municipio": True},
    {"nombre": "Ajangiz", "pais": "Euskal Herria", "codigo": 477, "tiene_municipio": True},
    {"nombre": "Alonsotegi", "pais": "Euskal Herria", "codigo": 2950, "tiene_municipio": True},
    {"nombre": "Amorebieta-Etxano", "pais": "Euskal Herria", "codigo": 19570, "tiene_municipio": True},
    {"nombre": "Amoroto", "pais": "Euskal Herria", "codigo": 392, "tiene_municipio": True},
    {"nombre": "Arakaldo", "pais": "Euskal Herria", "codigo": 160, "tiene_municipio": True},
    {"nombre": "Arantzazu", "pais": "Euskal Herria", "codigo": 389, "tiene_municipio": True},
    {"nombre": "Areatza", "pais": "Euskal Herria", "codigo": 1271, "tiene_municipio": True},
    {"nombre": "Arrankudiaga-Zollo", "pais": "Euskal Herria", "codigo": 991, "tiene_municipio": True},
    {"nombre": "Arratzu", "pais": "Euskal Herria", "codigo": 426, "tiene_municipio": True},
    {"nombre": "Arrieta", "pais": "Euskal Herria", "codigo": 580, "tiene_municipio": True},
    {"nombre": "Arrigorriaga", "pais": "Euskal Herria", "codigo": 11835, "tiene_municipio": True},
    {"nombre": "Artea", "pais": "Euskal Herria", "codigo": 754, "tiene_municipio": True},
    {"nombre": "Artzentales", "pais": "Euskal Herria", "codigo": 724, "tiene_municipio": True},
    {"nombre": "Atxondo", "pais": "Euskal Herria", "codigo": 1361, "tiene_municipio": True},
    {"nombre": "Aulesti", "pais": "Euskal Herria", "codigo": 660, "tiene_municipio": True},
    {"nombre": "Bakio", "pais": "Euskal Herria", "codigo": 2818, "tiene_municipio": True},
    {"nombre": "Balmaseda", "pais": "Euskal Herria", "codigo": 7593, "tiene_municipio": True},
    {"nombre": "Barakaldo", "pais": "Euskal Herria", "codigo": 101224, "tiene_municipio": True},
    {"nombre": "Barrika", "pais": "Euskal Herria", "codigo": 1533, "tiene_municipio": True},
    {"nombre": "Basauri", "pais": "Euskal Herria", "codigo": 40413, "tiene_municipio": True},
    {"nombre": "Bedia", "pais": "Euskal Herria", "codigo": 1114, "tiene_municipio": True},
    {"nombre": "Berango", "pais": "Euskal Herria", "codigo": 7453, "tiene_municipio": True},
    {"nombre": "Bermeo", "pais": "Euskal Herria", "codigo": 16755, "tiene_municipio": True},
    {"nombre": "Berriatua", "pais": "Euskal Herria", "codigo": 1216, "tiene_municipio": True},
    {"nombre": "Berriz", "pais": "Euskal Herria", "codigo": 4543, "tiene_municipio": True},
    {"nombre": "Bilbao", "pais": "Euskal Herria", "codigo": 346077, "tiene_municipio": True},
    {"nombre": "Busturia", "pais": "Euskal Herria", "codigo": 1644, "tiene_municipio": True},
    {"nombre": "Derio", "pais": "Euskal Herria", "codigo": 7071, "tiene_municipio": True},
    {"nombre": "Dima", "pais": "Euskal Herria", "codigo": 1450, "tiene_municipio": True},
    {"nombre": "Durango", "pais": "Euskal Herria", "codigo": 29767, "tiene_municipio": True},
    {"nombre": "Ea", "pais": "Euskal Herria", "codigo": 834, "tiene_municipio": True},
    {"nombre": "Elantxobe", "pais": "Euskal Herria", "codigo": 348, "tiene_municipio": True},
    {"nombre": "Elorrio", "pais": "Euskal Herria", "codigo": 7292, "tiene_municipio": True},
    {"nombre": "Erandio", "pais": "Euskal Herria", "codigo": 24411, "tiene_municipio": True},
    {"nombre": "Ereño", "pais": "Euskal Herria", "codigo": 277, "tiene_municipio": True},
    {"nombre": "Ermua", "pais": "Euskal Herria", "codigo": 15599, "tiene_municipio": True},
    {"nombre": "Errigoiti", "pais": "Euskal Herria", "codigo": 500, "tiene_municipio": True},
    {"nombre": "Etxebarri", "pais": "Euskal Herria", "codigo": 11780, "tiene_municipio": True},
    {"nombre": "Etxebarria", "pais": "Euskal Herria", "codigo": 782, "tiene_municipio": True},
    {"nombre": "Forua", "pais": "Euskal Herria", "codigo": 904, "tiene_municipio": True},
    {"nombre": "Fruiz", "pais": "Euskal Herria", "codigo": 551, "tiene_municipio": True},
    {"nombre": "Galdakao", "pais": "Euskal Herria", "codigo": 29285, "tiene_municipio": True},
    {"nombre": "Galdames", "pais": "Euskal Herria", "codigo": 834, "tiene_municipio": True},
    {"nombre": "Gamiz-Fika", "pais": "Euskal Herria", "codigo": 1395, "tiene_municipio": True},
    {"nombre": "Garai", "pais": "Euskal Herria", "codigo": 313, "tiene_municipio": True},
    {"nombre": "Gatika", "pais": "Euskal Herria", "codigo": 1644, "tiene_municipio": True},
    {"nombre": "Gautegiz Arteaga", "pais": "Euskal Herria", "codigo": 889, "tiene_municipio": True},
    {"nombre": "Gernika-Lumo", "pais": "Euskal Herria", "codigo": 17050, "tiene_municipio": True},
    {"nombre": "Getxo", "pais": "Euskal Herria", "codigo": 76104, "tiene_municipio": True},
    {"nombre": "Gizaburuaga", "pais": "Euskal Herria", "codigo": 197, "tiene_municipio": True},
    {"nombre": "Gordexola", "pais": "Euskal Herria", "codigo": 1674, "tiene_municipio": True},
    {"nombre": "Gorliz", "pais": "Euskal Herria", "codigo": 6031, "tiene_municipio": True},
    {"nombre": "Güeñes", "pais": "Euskal Herria", "codigo": 6740, "tiene_municipio": True},
    {"nombre": "Ibarrangelu", "pais": "Euskal Herria", "codigo": 672, "tiene_municipio": True},
    {"nombre": "Igorre", "pais": "Euskal Herria", "codigo": 4314, "tiene_municipio": True},
    {"nombre": "Ispaster", "pais": "Euskal Herria", "codigo": 751, "tiene_municipio": True},
    {"nombre": "Iurreta", "pais": "Euskal Herria", "codigo": 3662, "tiene_municipio": True},
    {"nombre": "Izurtza", "pais": "Euskal Herria", "codigo": 217, "tiene_municipio": True},
    {"nombre": "Karrantza Harana/Valle de Carranza", "pais": "Euskal Herria", "codigo": 2736, "tiene_municipio": True},
    {"nombre": "Kortezubi", "pais": "Euskal Herria", "codigo": 440, "tiene_municipio": True},
    {"nombre": "Lanestosa", "pais": "Euskal Herria", "codigo": 243, "tiene_municipio": True},
    {"nombre": "Larrabetzu", "pais": "Euskal Herria", "codigo": 2085, "tiene_municipio": True},
    {"nombre": "Laukiz", "pais": "Euskal Herria", "codigo": 1285, "tiene_municipio": True},
    {"nombre": "Leioa", "pais": "Euskal Herria", "codigo": 32446, "tiene_municipio": True},
    {"nombre": "Lekeitio", "pais": "Euskal Herria", "codigo": 7205, "tiene_municipio": True},
    {"nombre": "Lemoa", "pais": "Euskal Herria", "codigo": 3543, "tiene_municipio": True},
    {"nombre": "Lemoiz", "pais": "Euskal Herria", "codigo": 1318, "tiene_municipio": True},
    {"nombre": "Lezama", "pais": "Euskal Herria", "codigo": 2474, "tiene_municipio": True},
    {"nombre": "Loiu", "pais": "Euskal Herria", "codigo": 2297, "tiene_municipio": True},
    {"nombre": "Mallabia", "pais": "Euskal Herria", "codigo": 1160, "tiene_municipio": True},
    {"nombre": "Mañaria", "pais": "Euskal Herria", "codigo": 533, "tiene_municipio": True},
    {"nombre": "Markina-Xemein", "pais": "Euskal Herria", "codigo": 5037, "tiene_municipio": True},
    {"nombre": "Maruri-Jatabe", "pais": "Euskal Herria", "codigo": 1069, "tiene_municipio": True},
    {"nombre": "Mendata", "pais": "Euskal Herria", "codigo": 396, "tiene_municipio": True},
    {"nombre": "Mendexa", "pais": "Euskal Herria", "codigo": 412, "tiene_municipio": True},
    {"nombre": "Meñaka", "pais": "Euskal Herria", "codigo": 754, "tiene_municipio": True},
    {"nombre": "Morga", "pais": "Euskal Herria", "codigo": 431, "tiene_municipio": True},
    {"nombre": "Mundaka", "pais": "Euskal Herria", "codigo": 1843, "tiene_municipio": True},
    {"nombre": "Mungia", "pais": "Euskal Herria", "codigo": 17882, "tiene_municipio": True},
    {"nombre": "Munitibar-Arbatzegi Gerrikaitz", "pais": "Euskal Herria", "codigo": 470, "tiene_municipio": True},
    {"nombre": "Murueta", "pais": "Euskal Herria", "codigo": 321, "tiene_municipio": True},
    {"nombre": "Muskiz", "pais": "Euskal Herria", "codigo": 7342, "tiene_municipio": True},
    {"nombre": "Muxika", "pais": "Euskal Herria", "codigo": 1463, "tiene_municipio": True},
    {"nombre": "Nabarniz", "pais": "Euskal Herria", "codigo": 261, "tiene_municipio": True},
    {"nombre": "Ondarroa", "pais": "Euskal Herria", "codigo": 8179, "tiene_municipio": True},
    {"nombre": "Orozko", "pais": "Euskal Herria", "codigo": 2654, "tiene_municipio": True},
    {"nombre": "Ortuella", "pais": "Euskal Herria", "codigo": 8536, "tiene_municipio": True},
    {"nombre": "Otxandio", "pais": "Euskal Herria", "codigo": 1323, "tiene_municipio": True},
    {"nombre": "Plentzia", "pais": "Euskal Herria", "codigo": 4420, "tiene_municipio": True},
    {"nombre": "Portugalete", "pais": "Euskal Herria", "codigo": 44628, "tiene_municipio": True},
    {"nombre": "Santurtzi", "pais": "Euskal Herria", "codigo": 45506, "tiene_municipio": True},
    {"nombre": "Sestao", "pais": "Euskal Herria", "codigo": 27834, "tiene_municipio": True},
    {"nombre": "Sondika", "pais": "Euskal Herria", "codigo": 4523, "tiene_municipio": True},
    {"nombre": "Sopela", "pais": "Euskal Herria", "codigo": 14872, "tiene_municipio": True},
    {"nombre": "Sopuerta", "pais": "Euskal Herria", "codigo": 2731, "tiene_municipio": True},
    {"nombre": "Sukarrieta", "pais": "Euskal Herria", "codigo": 355, "tiene_municipio": True},
    {"nombre": "Trucios-Turtzioz", "pais": "Euskal Herria", "codigo": 521, "tiene_municipio": True},
    {"nombre": "Ubide", "pais": "Euskal Herria", "codigo": 161, "tiene_municipio": True},
    {"nombre": "Ugao-Miraballes", "pais": "Euskal Herria", "codigo": 4164, "tiene_municipio": True},
    {"nombre": "Urduliz", "pais": "Euskal Herria", "codigo": 5447, "tiene_municipio": True},
    {"nombre": "Urduña/Orduña", "pais": "Euskal Herria", "codigo": 4114, "tiene_municipio": True},
    {"nombre": "Usansolo", "pais": "Euskal Herria", "codigo": 4520, "tiene_municipio": True},
    {"nombre": "Valle de Trápaga-Trapagaran", "pais": "Euskal Herria", "codigo": 11911, "tiene_municipio": True},
    {"nombre": "Zaldibar", "pais": "Euskal Herria", "codigo": 3031, "tiene_municipio": True},
    {"nombre": "Zalla", "pais": "Euskal Herria", "codigo": 8314, "tiene_municipio": True},
    {"nombre": "Zamudio", "pais": "Euskal Herria", "codigo": 3280, "tiene_municipio": True},
    {"nombre": "Zaratamo", "pais": "Euskal Herria", "codigo": 1613, "tiene_municipio": True},
    {"nombre": "Zeanuri", "pais": "Euskal Herria", "codigo": 1247, "tiene_municipio": True},
    {"nombre": "Zeberio", "pais": "Euskal Herria", "codigo": 1081, "tiene_municipio": True},
    {"nombre": "Zierbena", "pais": "Euskal Herria", "codigo": 1502, "tiene_municipio": True},
    {"nombre": "Ziortza-Bolibar", "pais": "Euskal Herria", "codigo": 402, "tiene_municipio": True},
]

def seed_municipios():
    for data in municipios_seed:
        # evitar duplicados
        existe = Municipio.query.filter_by(codigo=data["codigo"]).first()
        if existe:
            continue

        municipio = Municipio(
            nombre=data["nombre"],
            pais=data["pais"],
            codigo=data["codigo"],
            tiene_municipio=data["tiene_municipio"]
        )

        db.session.add(municipio)

    db.session.commit()