"""Cambiar provincia_id a codigo_provincia en Capital

Revision ID: 0498ec7067f7
Revises: 2cb3fcaf67be
Create Date: 2026-03-29 12:02:32.862187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0498ec7067f7'
down_revision = '2cb3fcaf67be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate table for SQLite compatibility
    op.rename_table('capitales', 'capitales_old')
    op.create_table('capitales',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('codigo_provincia', sa.String(length=2), nullable=False),
        sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True),
        sa.ForeignKeyConstraint(['codigo_provincia'], ['provincias.codigo']),
        sa.PrimaryKeyConstraint('id')
    )
    # Copy data
    op.execute('INSERT INTO capitales (id, nombre, codigo_provincia, latitud, longitud) SELECT c.id, c.nombre, p.codigo, c.latitud, c.longitud FROM capitales_old c JOIN provincias p ON c.provincia_id = p.id')
    op.drop_table('capitales_old')

    with op.batch_alter_table('provincias', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_provincias_codigo', ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provincias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('capitales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provincia_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'provincias', ['provincia_id'], ['id'])
        batch_op.drop_column('codigo_provincia')

    # ### end Alembic commands ###
