"""fix fk name

Revision ID: 0d401f93be88
Revises: c8f3f1508665
Create Date: 2026-03-26 14:12:04.679860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d401f93be88'
down_revision = 'c8f3f1508665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_provincia', sa.String(length=2), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('codigo_provincia', 'provincias', ['codigo_provincia'], ['codigo'])
        batch_op.drop_column('provincia_id')

    with op.batch_alter_table('provincias', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provincias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('capitales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provincia_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('codigo_provincia', type_='foreignkey')
        batch_op.create_foreign_key(None, 'provincias', ['provincia_id'], ['id'])
        batch_op.drop_column('codigo_provincia')

    # ### end Alembic commands ###
