"""Initial tables

Revision ID: 383093a78c74
Revises: 
Create Date: 2026-03-27 11:54:21.904326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383093a78c74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=10), nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('tiene_municipio', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('capitales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('provincia_id', sa.String(length=2), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('codigo_postal', sa.Integer(), nullable=False),
    sa.Column('poblacion', sa.Integer(), nullable=False),
    sa.Column('area_km2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('municipios')
    op.drop_table('capitales')
    op.drop_table('provincias')
    # ### end Alembic commands ###
